version: '3'

services:

  zookeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - discovery.type=single-node

  logstash:
    image: logstash:8.4.3
    container_name: logstash
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    image: kibana:8.4.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - mongo
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    links:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
